---
title: Simeon's Blog
baseurl: "/"
desc: A minimal blog for off-topic blog entries.
about: Father, Husband & Coder
image: /images/slyu.jpg
excerpt_separator: "<!-- more -->"
markdown: kramdown
gems:
- jekyll-paginate
exclude:
  - .jekyll-metadata
  - README.md
  - CNAME
paginate: 10
paginate_path: "/:num/"
highlighter: rouge
permalink: pretty
